parameters:
    ###> DEFAULT ###
    
    env(GrinWay_COMMAND_DISPLAY_INIT_HELP_MESSAGE): '1'
    grin_way_command.display_init_help: '%env(bool:GrinWay_COMMAND_DISPLAY_INIT_HELP_MESSAGE)%'
    
    grin_way_command.progress_bar_spin:
        -    " ⠋"
        -    " ⠙"
        -    " ⠚"
        -    " ⠒"
        -    " ⠂"
        -    " ⠂"
        -    "⠒ "
        -    "⠲ "
        -    "⠴ "
        -    "⠦ "
        -    "⠖ "
        -    "⠒ "
        -    "⠐ "
        -    "⠐ "
        -    " ⠒"
        -    " ⠓"
        -    " ⠋"
        -    "⡀⠀"
        -    "⠄⠀"
        -    "⢂⠀"
        -    "⡂⠀"
        -    "⠅⠀"
        -    "⢃⠀"
        -    "⡃⠀"
        -    "⠍⠀"
        -    "⢋⠀"
        -    "⡋⠀"
        -    "⠍⠁"
        -    "⢋⠁"
        -    "⡋⠁"
        -    "⠍⠉"
        -    "⠋⠉"
        -    "⠋⠉"
        -    "⠉⠙"
        -    "⠉⠙"
        -    "⠉⠩"
        -    "⠈⢙"
        -    "⠈⡙"
        -    "⢈⠩"
        -    "⡀⢙"
        -    "⠄⡙"
        -    "⢂⠩"
        -    "⡂⢘"
        -    "⠅⡘"
        -    "⢃⠨"
        -    "⡃⢐"
        -    "⠍⡐"
        -    "⢋⠠"
        -    "⡋⢀"
        -    "⠍⡁"
        -    "⢋⠁"
        -    "⡋⠁"
        -    "⠍⠉"
        -    "⠋⠉"
        -    "⠋⠉"
        -    "⠉⠙"
        -    "⠉⠙"
        -    "⠉⠩"
        -    "⠈⢙"
        -    "⠈⡙"
        -    "⠈⠩"
        -    "⠀⢙"
        -    "⠀⡙"
        -    "⠀⠩"
        -    "⠀⢘"
        -    "⠀⡘"
        -    "⠀⠨"
        -    "⠀⢐"
        -    "⠀⡐"
        -    "⠀⠠"
        -    "⠀⢀"
        
    ###< DEFAULT ###
    env(GrinWay_COMMAND_PATH_TO_PDF_CONVERTER): '%kernel.project_dir%/public/bundles/grinwaycommand/exec/docto.exe'
    grin_way_command.path_to_pdf_converter: '%env(grin_way_env_normalize_path:grin_way_env_is_exists_file:grin_way_env_is_absolute_path:resolve:GrinWay_COMMAND_PATH_TO_PDF_CONVERTER)%'
    
    env(GrinWay_COMMAND_PATH_TO_NIRCMD):   '%kernel.project_dir%/public/bundles/grinwaycommand/exec/nircmd.exe'
    grin_way_command.path_to_nircmd:         '%env(grin_way_env_normalize_path:grin_way_env_is_exists_path:grin_way_env_is_exists_file:resolve:GrinWay_COMMAND_PATH_TO_NIRCMD)%'

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> !BORROW THESE VALUES! ###
            $appEnv:                        '%grin_way_command.app_env%'
            $progressBarSpin:               '%grin_way_command.progress_bar_spin%'
            $grinWayCommandPathToPdfConverter:   '%grin_way_command.path_to_pdf_converter%'
            $grinWayCommandPathToNircmd:         '%grin_way_command.path_to_nircmd%'
            
            ###> SERVICES ###
            $devLogger: '@monolog.logger.grin_way_command.dev_logger'
            ###< SERVICES ###
            
            ###> LIB SERVICES ###
            $t: '@translator.default'
            ###< LIB SERVICES ###
            
            ###< !BORROW THESE VALUES! ###
            
            ###> BUNDLE SERVICES ###
            $grinWayServiceCarbonFactory:    '@grin_way_service.carbon_factory'
            ###< BUNDLE SERVICES ###
            